apiVersion: v1
kind: Service
metadata:
  name: authservice
  labels:
    app: authservice
spec:
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
