name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker images
        run: |
          docker build -f .\src\main\java\com\example\authservice\Dockerfile -t com/example/authservice .
          docker build -f .\src\main\java\com\example\orderservice\Dockerfile -t com/example/orderservice .
          docker build -f .\src\main\java\com\example\userservice\Dockerfile -t com/example/useservice .

      - name: Push Docker images
        run: |
          docker push homework4/authservice:latest
          docker push homework4/orderservice:latest
          docker push homework4/userservice:latest
        if: github.ref == 'refs/heads/master'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set up kubectl
        run: kubectl version --client

      - name: Deploy authservice to Kubernetes
        run: kubectl apply -f ./src/main/java/com/example/authservice/kubernetes/

      - name: Deploy orderservice to Kubernetes
        run: kubectl apply -f ./src/main/java/com/example/orderservice/kubernetes/

      - name: Deploy userservice to Kubernetes
        run: kubectl apply -f ./src/main/java/com/example/userservice/kubernetes/

