name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptium'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker images
        run: |
          docker build -t your-docker-repo/authservice ./src/main/java/com/example/authservice
          docker build -t your-docker-repo/orderservice ./src/main/java/com/example/orderservice
          docker build -t your-docker-repo/userservice ./src/main/java/com/example/userservice

      - name: Push Docker images
        run: |
          docker push your-docker-repo/authservice:latest
          docker push your-docker-repo/orderservice:latest
          docker push your-docker-repo/userservice:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set up kubectl
        run: kubectl version --client

      - name: Deploy authservice to Kubernetes
        run: kubectl apply -f ./src/main/java/com/example/authservice/kubernetes/

      - name: Deploy orderservice to Kubernetes
        run: kubectl apply -f ./src/main/java/com/example/orderservice/kubernetes/

      - name: Deploy userservice to Kubernetes
        run: kubectl apply -f ./src/main/java/com/example/userservice/kubernetes/

