name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker images
        run: |
          # Build and tag authservice Docker image
          docker build -f ./src/main/java/com/example/authservice/Dockerfile -t authservice:latest .
          docker tag authservice:latest stefanija052/homework4-authservice:latest

          # Build and tag orderservice Docker image
          docker build -f ./src/main/java/com/example/orderservice/Dockerfile -t orderservice:latest .
          docker tag orderservice:latest stefanija052/homework4-orderservice:latest

          # Build and tag userservice Docker image
          docker build -f ./src/main/java/com/example/userservice/Dockerfile -t userservice:latest .
          docker tag userservice:latest stefanija052/homework4-userservice:latest

      - name: Push Docker images
        run: |
          docker push stefanija052/homework4-authservice:latest
          docker push stefanija052/homework4-orderservice:latest
          docker push stefanija052/homework4-userservice:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=docker --embed-certs

      - name: Set up Kubernetes configuration
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set up Kubernetes certificates
        run: |
          mkdir -p ~/.minikube/profiles/minikube
          echo "${{ secrets.KUBE_CLIENT_CERT }}" > ~/.minikube/profiles/minikube/client.crt
          echo "${{ secrets.KUBE_CLIENT_KEY }}" > ~/.minikube/profiles/minikube/client.key
          echo "${{ secrets.KUBE_CA_CERT }}" > ~/.minikube/ca.crt

      - name: Set up kubectl
        run: kubectl version --client

      - name: Deploy authservice to Kubernetes
        run: kubectl apply -f ./src/main/java/com/example/authservice/kubernetes/

      - name: Deploy orderservice to Kubernetes
        run: kubectl apply -f ./src/main/java/com/example/orderservice/kubernetes/

      - name: Deploy userservice to Kubernetes
        run: kubectl apply -f ./src/main/java/com/example/userservice/kubernetes/
