name: CI/CD Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t myapp-dev .

      - name: Push Docker image (optional)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag myapp-dev myrepo/myapp-dev:latest
          docker push myrepo/myapp-dev:latest